name: Release Tao extension

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  auto-release:
    name: Automated Tao extension release
    runs-on: ubuntu-latest
    
    steps:    
      - name: clone the repository
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0  #avoid unrelated history error
          token: ${{ secrets.SEMVER_GH_TOKEN }} #bypass branch protection rule

      - name: Configure git user
        #configuring git for runner
        run: |
          git config --global user.name "oat-github-bot"
          git config --global user.email "oat-github-bot@taotesting.com"                            


      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest

      - name: npm install
        env: 
          GITHUB_TOKEN: ${{ secrets.SEMVER_GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.CI_NPM_RELEASE_TOKEN }}
        run: |
          npm i -g
          npm i update-notifier 
          git status

      - name: run release tool
        env: 
          GITHUB_TOKEN: ${{ secrets.SEMVER_GH_TOKEN }}
        run: |
          npm --version
          # publish --registry https://registry.npmjs.org/
          #create tag and release a new version
          taoRelease npmRelease --release-branch master --no-interactive

          #Release branch will be different for each repository, make necessary changes. 
